Fix the error code to properly display
SublimeLinter/SublimeLinter-bandit pull request #4
Opened 2018-03-22 05:25 UTC by ericwb

In a previous commit [1], an attempt was made to add the error code
to the resulting message. However, this did not work.

The correct way to get the error code is to override the result
of the error or warning variable.

This patch will now show the message as:
 21:1 warning bandit: B303 Use of insecure MD2, MD4, or MD5 hash function.

instead of:
 21:1 warning bandit: Medium Use of insecure MD2, MD4, or MD5 hash function.

[1] https://github.com/SublimeLinter/SublimeLinter-bandit/pull/3

Signed-off-by: Eric Brown <browne@vmware.com>

2018-03-22 07:37 UTC, braver commented
Why didn't it work? Do you have some examples?

2018-03-27 06:39 UTC, ericwb commented
@braver It didn't work previously because SublimeLinter has no handling of the regex "code" variable.  To get that value displayed, it must be part of "message" or "error", "warning" group variables.  I want it to display like pylint, which puts the value in error or warning variables.

2018-03-27 07:06 UTC, braver commented
I would've sworn we handle `(?P<code>)` groups in the regex, but apparantly not. Wouldn't that be a more elegant approach? (cc @kaste )

2018-03-27 08:45 UTC, kaste commented
We did not tackle this for SL4. pykong and FichteFoll just added the sugar namedtuple abstraction LintMatch, without making the whole matching/parsing errors thing modern and flexible. (I need to make similar stuff in eslint).

@ericwb The super call is just `super().split_match...`

2018-03-30 16:25 UTC, braver commented on linter.py
> +            self.__class__, self).split_match(match)
Use super().split_match here

2018-03-30 16:26 UTC, braver requested changes

2018-03-30 16:26 UTC, braver commented on linter.py
> +            self.__class__, self).split_match(match)
Use super().split_match here

2018-04-25 19:06 UTC, braver commented on linter.py
> +            self.__class__, self).split_match(match)
👋

2018-12-16 17:58 UTC, braver commented
Closed because of inactivity. @ericwb If you want to pick this up again let me know.

2018-12-16 17:58 UTC, closed without merging